# Generated by Django 3.1.4 on 2020-12-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathhistory',
            name='result',
            field=models.IntegerField(),
        ),
    ]
