# Generated by Django 3.1.4 on 2020-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.CharField(max_length=60)),
                ('result', models.IntegerField(max_length=60)),
            ],
        ),
    ]
