version: '3.7'

services:
    api:
        container_name: "PythonAPIcontainer"
        build: .
        command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code

        ports:
            - "8000:8000"

